name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install packages
      run: |
        pip install Flask bandit pytest

    - name: Run simple test
      run: |
        # Просто проверяем что app.py существует
        if [ -f "app.py" ]; then
          echo "✓ app.py найден"
          python -c "print('Python работает нормально')"
        else
          echo "✗ app.py не найден"
          exit 1
        fi

    - name: Run bandit security
      run: |
        bandit -r . || echo "Bandit проверка завершена"

  changelog:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create simple changelog
      run: |
        echo "# Changelog" > CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "## [v1.0.0] - $(date +'%Y-%m-%d')" >> CHANGELOG.md
        echo "  - Initial release" >> CHANGELOG.md
        echo "" >> CHANGELOG.md
        
        # Показываем что создали
        cat CHANGELOG.md

    - name: Upload CHANGELOG as artifact
      uses: actions/upload-artifact@v3
      with:
        name: changelog
        path: CHANGELOG.md